### ISSUE TITLE
How Do I use this Library?

### ISSUE THREAD

**Issue by TealEgg** [danielbob999/TackEngineLib#7]
Hello. Lately I've been looking for 2d game frameworks and I found this one. I was wondering if you could explain how to start using this library and if there are any examples. Thanks in advance!

**Comment by danielbob999** [comment]
Hi TealEgg,

Currently TackEngine is in a very "in development" stage. There are many issues and lots of bugs still to iron out. 

If you are still interested, I would be happy to put up some documentation and a few example projects on how to use the framework.

Thanks

Daniel

**Comment by TealEgg** [comment]
Hello, I think a few sample projects would be good so I can see how to format the project. A quick question though, how does the coordinate system work (like where's the origin, are the units in pixels or just in general world coordinates, etc.)? Thanks in advance!
